# Generated by Django 5.1.6 on 2025-03-22 09:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_alter_datauser_created_question_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datauser',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 22, 14, 44, 41, 169877)),
        ),
    ]
