# Generated by Django 5.1.6 on 2025-04-03 07:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0009_alter_datauser_created_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datauser',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 3, 13, 26, 30, 859101)),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='images/'),
        ),
    ]
