# Generated by Django 5.1.6 on 2025-04-15 11:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0010_alter_datauser_created_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datauser',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 15, 17, 10, 46, 266099)),
        ),
    ]
