# Generated by Django 5.1.6 on 2025-04-16 05:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0011_alter_datauser_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datauser',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 16, 11, 13, 50, 811758)),
        ),
    ]
