# Generated by Django 5.1.6 on 2025-04-16 10:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0014_remove_post_image_alter_datauser_created_postimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='datauser',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 16, 16, 1, 25, 529867)),
        ),
        migrations.DeleteModel(
            name='PostImage',
        ),
    ]
